

export const sampleFarmerTableData = [
    {
        id: 1,
        firstName: 'James',
        lastName: 'Peddigo',
        riceBags: 23,
        beansBags: 14,
        maizeBags: 29,
        potatoeBags: 8,
        groundNutBags: 17,
    },
    {
        id: 2,
        firstName: 'Umar',
        lastName: 'Sanda',
        riceBags: 44,
        beansBags: 10,
        maizeBags: 32,
        potatoeBags: 11,
        groundNutBags: 21,
    },
    {
        id: 3,
        firstName: 'Paul',
        lastName: 'Nwanchukwu',
        riceBags: 17,
        beansBags: 19,
        maizeBags: 21,
        potatoeBags: 14,
        groundNutBags: 20,
    },
    {
        id: 4,
        firstName: 'Joseph',
        lastName: 'Folade',
        riceBags: 31,
        beansBags: 14,
        maizeBags: 29,
        potatoeBags: 9,
        groundNutBags: 22,
    },
    {
        id: 5,
        firstName: 'Jerimiah',
        lastName: 'Figgo',
        riceBags: 11,
        beansBags: 22,
        maizeBags: 1,
        potatoeBags: 17,
        groundNutBags: 19,
    },
    {
        id: 6,
        firstName: 'Uche',
        lastName: 'Orakwe',
        riceBags: 18,
        beansBags: 9,
        maizeBags: 8,
        potatoeBags: 14,
        groundNutBags: 0,
    },
    {
        id: 7,
        firstName: 'Atiku',
        lastName: 'Balarabe',
        riceBags: 23,
        beansBags: 14,
        maizeBags: 29,
        potatoeBags: 8,
        groundNutBags: 17,
    },
    {
        id: 8,
        firstName: 'Enyo',
        lastName: 'Adanu',
        riceBags: 44,
        beansBags: 10,
        maizeBags: 32,
        potatoeBags: 11,
        groundNutBags: 21,
    },
    {
        id: 9,
        firstName: 'Mustafa',
        lastName: 'Badmus',
        riceBags: 17,
        beansBags: 19,
        maizeBags: 21,
        potatoeBags: 14,
        groundNutBags: 20,
    },
    {
        id: 10,
        firstName: 'Oke',
        lastName: 'Oghennedoro',
        riceBags: 31,
        beansBags: 14,
        maizeBags: 29,
        potatoeBags: 9,
        groundNutBags: 22,
    },
    // {
    //     id: 11,
    //     firstName: 'Isreal',
    //     lastName: 'Sambo',
    //     riceBags: 11,
    //     beansBags: 22,
    //     maizeBags: 1,
    //     potatoeBags: 17,
    //     groundNutBags: 19,
    // },
    // {
    //     id: 12,
    //     firstName: 'Jideofor',
    //     lastName: 'Agwu',
    //     riceBags: 18,
    //     beansBags: 9,
    //     maizeBags: 8,
    //     potatoeBags: 14,
    //     groundNutBags: 0,
    // },
];

export const farmerPayload = {
    responseCode: 200,
    responseText: 'Farmers loaded successfully',
    payload: {
        farmerList: sampleFarmerTableData,
        settings: {
            total: 100,
            limit: 10,
        }
    }
}